services:
  - type: web
    name: portfolioai
    runtime: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: JAVA_OPTS
        value: "-Xmx220m -XX:+UseSerialGC -Xss512k"