micronaut:
  application:
    name: portfolioai

portfolioai:
  rag:
    max-results: 4
    min-score: 0.65

langchain4j:
  open-ai:
    api-key: ${GROQ_API_KEY}
    chat-model:
      base-url: https://api.groq.com/openai/v1
      model-name: openai/gpt-oss-20b
      temperature: 0.2
      timeout: 90s


